### ISSUE TITLE
Cannot update to current version on JRuby

### ISSUE THREAD

**Issue by batasrki** [kristianmandrup/cream#9]
See https://github.com/kristianmandrup/cancan-permits/issues#issue/4. Same issue for this gem, which kinda makes sense.

However, it's a show stopper for me.

**Comment by kristianmandrup** [comment]
I am using log4r for logging. Log4r apparently uses _scribe_ which again uses _thrift_:

https://github.com/fauna/scribe

I will see what I can do to get around this ;)

Looks like this might provide a way!?

https://github.com/fauna/thrift-rb/blob/master/Rakefile

As can be seen from this commit it should support both Rubinius and JRuby.

https://github.com/fauna/thrift-rb/commit/33afdb641d0804a5212cb65d60cf99382f5526a5

So I think that making a version _scribe-rb_ that uses _thrift-rb_ and then have _log4r-color_ include _scribe-rb_ instead of _scribe_ would make it work on all platforms!?

Maybe this would help?

https://github.com/jmhodges/thrift-rb/commit/69939cfb702067395935c4e1611c47eaf625721a

Except when I run _$ rake install_ I get an error. The rakefile needs to be updated to RSpec 2 in my case. So I removed the RSpec stuff.

Now I can install thrift without native extensions:

https://github.com/kristianmandrup/thrift-rb

$ rake install

Please see if you can go from here ;)

Maybe if you insert something like this at the top of your Gemfile it would work!?

gem 'thrift', :git => 'https://github.com/kristianmandrup/thrift-rb.git'
gem 'thrift_client', :git => 'https://github.com/kristianmandrup/thrift_client.git'

**Comment by batasrki** [comment]
Yeah, I'll make an example app and see if that works. What about specifying that as a dependency in cream using the :platforms option? I worked around a few gems for my app in that fashion.

**Comment by kristianmandrup** [comment]
I am currently very busy implementing a Rails web app for a customer. 
Please, if you can patch cream with a platform option that would be awesome!
Then just send me a pull request. I recommend you use the head/master of Cream as it should have the latest fixes. Good luck!

**Comment by batasrki** [comment]
No problem. I'll see if that'll fix it and make the pull request.

**Comment by kristianmandrup** [comment]
Did you ever make that patch? Right now I'm trying to add logging as an optional option in the generators to avoid this issue. Check out the latest logging branch (needs testing).

**Comment by batasrki** [comment]
No, I didn't get a chance to. I also found a bug in the JRuby interpreter regarding MongoMapper, yet another show stopper. I reported it and Charles Nutter had it fixed for 1.6 RC2. I switched to 1.9.2 to continue my app development.

I'll see if I can carve out some time to test this for you.
